### ISSUE TITLE
Scalariform settings pane has disappeared with IntelliJ 2016

### ISSUE THREAD

**Issue by iantabolt** [thesamet/scalariform-intellij-plugin#5]
IntelliJ 15 (Ultimate 15.0.4):

![image](https://cloud.githubusercontent.com/assets/5240310/16495005/8ebc483c-3eb9-11e6-9e2d-472a7de47d83.png)

IntelliJ 2016 (Ultimate 2016.1.3):

![image](https://cloud.githubusercontent.com/assets/5240310/16495075/d4625250-3eb9-11e6-9e36-912b47802f12.png)

Note that the plugin is still installed, and still works (I'm pretty sure it even carried over the settings from my 15 installation).

From 2016:

![image](https://cloud.githubusercontent.com/assets/5240310/16495133/ff71e37a-3eb9-11e6-8432-c1ae5d24d7f0.png)

**Comment by anshumans** [comment]
+1

**Comment by melodious** [comment]
+1
